# Generated by Django 5.1.1 on 2024-09-13 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDisplay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, default=0, null=True, verbose_name='収入')),
                ('other_income', models.IntegerField(blank=True, default=0, null=True, verbose_name='その他の収入')),
                ('food_expenses', models.IntegerField(blank=True, default=0, null=True, verbose_name='食費')),
                ('rent_utilities', models.IntegerField(blank=True, default=0, null=True, verbose_name='家賃＋光熱費')),
                ('entertainment_transportation', models.IntegerField(blank=True, default=0, null=True, verbose_name='娯楽費＋交通費')),
                ('clothing', models.IntegerField(blank=True, default=0, null=True, verbose_name='衣服')),
                ('other_expenses', models.IntegerField(blank=True, default=0, null=True, verbose_name='その他の支出')),
                ('page_date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
