# Generated by Django 5.1.1 on 2024-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddisplay',
            name='page_date',
            field=models.DateField(null=True, verbose_name='日付'),
        ),
    ]
